### ISSUE TITLE
[Testing Party] Can't Login With Provided Credentials 

### ISSUE THREAD

**Issue by StephanieHou** [gcivil-nyu-org/INET-Monday-Spring2023-Team-4#128]
Hi Team 4! I wanted to call out that I can't seem to login on your site with the provided test accounts. Can you please check if it is working on site on your end? Can test again after.

**Comment by JinweiZhu** [comment]
Me too.

**Comment by zl3952** [comment]
Hello all, seems like we have the environment setup wrong. You should all be good now! Thanks
